server:
  port: 8080

spring:
  data:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: unac aqdj kspv tjah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
